- src/model/travel-time.fixtures.ts
- src/styles/common.ts
https://jira.camptocamp.com/browse/GSREN3D-250
- 250: update travel time station name
- updated dimmed color for unselected line
> GSREN3D-250: update travel time, update dimmed line color

- src/model/travel-time.fixtures.ts
https://jira.camptocamp.com/browse/GSREN3D-251
- Update travel time data.
> GSREN3D-251: Update travel time data.

- README.md
https://jira.camptocamp.com/browse/GSREN3D-XXX
> Fix url on README

- src/components/map/CompassComponent.vue
- src/components/map/buttons/NavigationButtons.vue
https://jira.camptocamp.com/browse/GSREN3D-255
- Set camera position to null to force its recalculation
> GSREN3D-255: Fix tilt and zoom issue on 3D map

- src/components/map/MapComponent.vue
- src/helpers/layerHelper.ts
- src/helpers/traveltimesHelper.ts
https://jira.camptocamp.com/browse/GSREN3D-264
- Use fetch data to fix the issue with unloaded data
> GSREN3D-264: Use fetch data to handle unfinished loading data for travel time.

- src/styles/arrow.ts
https://jira.camptocamp.com/browse/GSREN3D-264
- Still need improvement (i.e. make the arrow not under the ground and put some offset from the station)
> GSREN3D-264: Make the arrow in 3D.

- package-lock.json
- src/components/home/BackButton.vue
- src/views/StationView.vue
https://jira.camptocamp.com/browse/GSREN3D-265
> Bug fix: GSREN3D-265: Go to line view when going back from station view

- src/components/map/MapComponent.vue
https://jira.camptocamp.com/browse/GSREN3D-272
- Use `layer.fetchData` to fix the issue
- I need to fix this issue first before implementing the arrow style
> GSREN3D-272: Show POI on direct accest to line and station view.

- src/App.vue
- src/components/home/BackButton.vue
- src/components/home/FooterArea.vue
- src/components/home/LegalLink.story.vue
- src/components/home/LegalLink.vue
- src/components/ui/UiButton.vue
- src/components/ui/UiLinkFooter.vue
- tailwind.config.cjs
https://jira.camptocamp.com/browse/GSREN3D-263
- add links to legal notice when the side panel is closed
- Fix the bug for the photo gallery
- Fix a small issue on the back button (found when implementing a modal dialog)
- Modal is no longer needed
> GSREN3D-263: legal notice links

- src/components/map/MapComponent.vue
- src/helpers/traveltimesHelper.ts
- src/services/RennesApp.ts
- src/services/arrow.ts
https://jira.camptocamp.com/browse/GSREN3D-298
- Use the height of the station for the start and end of the arrow. When we have the offset for the arrow, it should be look better
> GSREN3D-298: fix arrow pointing to ground

- src/stores/componentsAboveMapStore.ts
- src/stores/stations.ts
GSREN3D-299 : label in 3D performance problem
https://jira.camptocamp.com/browse/GSREN3D-299
In 3D, update position of components only when viewpoint change
> GSREN3D-299 : label in 3D performance problem

- src/components/home/SidePanel.vue
- src/components/map/aboveMap/ComponentsAboveMap.vue
- src/components/map/aboveMap/LabelLine.vue
- src/interactions/clickAndMoveInteraction.ts
- src/map.config.json
- src/services/RennesApp.ts
- src/stores/componentsAboveMapStore.ts
- src/stores/interactionMap.ts
- src/stores/layers.ts
- src/views/HomeView.vue
- src/views/LineView.vue
- src/views/StationView.vue
- src/views/TravelTimesView.vue
GSREN3D-266 - Make line clikable and label
https://jira.camptocamp.com/browse/GSREN3D-266
Make line clickable and label
https://user-images.githubusercontent.com/121813008/215770460-56cf8819-072f-4fa8-93e0-d572d3825b0d.mp4
> GSREN3D-266 - Make line clikable and label

- src/App.vue
- src/components/station/ItemService.vue
- src/interactions/clickAndMoveInteraction.ts
- src/model/services.model.ts
- src/services/RennesApp.ts
- src/services/filter.ts
- src/services/parking.ts
- src/views/LineView.vue
GSREN3D-307 : Fix bugs parking, click station & img service
https://jira.camptocamp.com/browse/GSREN3D-307
Fix bug : fetch parkings by station instead of fetch parking by line
Fix bug: img service online are not working
Fix bug: click on another station on station view doesn't work
> GSREN3D-307 : Fix bugs parking, click station & img service

- src/services/parking.ts
fix line 2 : one parking is missing
https://jira.camptocamp.com/browse/GSREN3D-307
One parking is missing on line 2
> fix line 2 : one parking is missing

- src/components/map/buttons/NavigationButtons.vue
fix size navigation button on home page in 3D
> fix size navigation button on home page in 3D

- src/stores/layers.ts
- src/views/HomeView.vue
- src/views/LineView.vue
- src/views/StationView.vue
- src/views/TravelTimesView.vue
https://jira.camptocamp.com/browse/GSREN3D-318
- Always hide metro bus bike layer when change page.
> GSREN3D-318: Always hide metro bus bike layer when change page.

- src/components/map/MapComponent.vue
- src/interactions/clickAndMoveInteraction.ts
- src/services/poi.ts
- src/stores/interactionMap.ts
- src/styles/common.ts
GSREN3D-327 - Home page and line page: Labeling POI while Hoovering
https://jira.camptocamp.com/browse/GSREN3D-327
https://user-images.githubusercontent.com/121813008/220166927-db80f987-c6ca-410b-ba0a-731751ff4985.mp4
> GSREN3D-327 - Home page and line page: Labeling POI while Hoovering

- src/components/map/aboveMap/LabelStation.vue
- src/views/TravelTimesView.vue
GSREN3D-319 : station label wrong display
https://jira.camptocamp.com/browse/GSREN3D-319
https://user-images.githubusercontent.com/121813008/220142820-cb7394f1-6df1-402a-bfec-2f1c23b4c215.mp4
> GSREN3D-319 : station label wrong display

- src/components/map/MapComponent.vue
- src/helpers/viewpointHelper.ts
- src/services/api.client.ts
https://jira.camptocamp.com/browse/GSREN3D-322
- Use constant distance for the station viewpoint.
> GSREN3D-322: Better viewpoint for station.

- src/components/map/planning/PlanningMapComponent.vue
https://jira.camptocamp.com/browse/GSREN3D-317
- Add positioning on UiLineButton overall for better placement when zoomed in
> GSREN3D-317: Add positioning on UiLineButton overlay for better placement.

- src/interactions/clickAndMoveInteraction.ts
- src/services/poi.ts
- src/services/setDistanceDisplayCondition.ts
- src/stores/interactionMap.ts
- src/views/LineView.vue
GSREN3D-309 fix: POI selection by line not working well
https://jira.camptocamp.com/browse/GSREN3D-309
When we go to station from another station, the poi are update
https://user-images.githubusercontent.com/121813008/222378810-b0e6fa2c-f48c-469b-b7f2-7682cf56bbf1.mp4
3D :
- Display POI by distance
- Fix: display and undisplay name on hover poi
https://user-images.githubusercontent.com/121813008/222753763-4dc1b411-a88a-4853-8abf-f8e01556cd19.mp4
> GSREN3D-309 fix: POI selection by line not working well

- src/components/map/CompassComponent.vue
GSREN3D-306: fix compass rotattion map
https://jira.camptocamp.com/browse/GSREN3D-306
> GSREN3D-306: fix compass rotattion map

- package-lock.json
- package.json
- src/components/map/CompassComponent.vue
- src/components/map/buttons/NavigationButtons.vue
- src/services/viewStyle.ts
GSREN3D-281 - descriptions buttons 3D and compass
https://jira.camptocamp.com/browse/GSREN3D-281
Linked to this PR: https://github.com/sigrennesmetropole/cooperation_jn_common_ui/pull/20
> GSREN3D-281 - descriptions buttons 3D and compass

- src/views/TravelTimesView.vue
GSREN3D-319 - fix color label station on travel time page
https://jira.camptocamp.com/browse/GSREN3D-319
Before 
After fix
> GSREN3D-319 - fix color label station on travel time page

- src/components/ui/UiOverflowContainer.vue
- src/components/ui/UiPhotoGalery.vue
- src/views/HomeView.vue
- src/views/TravelTimesView.vue
GSREN3D-310 - fix theorical travel time
https://jira.camptocamp.com/browse/GSREN3D-310
> GSREN3D-310 - fix theorical travel time

- src/App.vue
- src/components/home/BackButton.vue
- src/components/map/aboveMap/LabelLine.vue
- src/interactions/clickAndMoveInteraction.ts
- src/stores/panels.ts
- src/stores/stations.ts
- src/views/StationView.vue
GSREN3D-331 - back button available with side panel retract
https://jira.camptocamp.com/browse/GSREN3D-331
> GSREN3D-331 - back button available with side panel retract

- src/services/viewStyle.ts
- src/styles/common.ts
- src/styles/line.ts
- src/styles/trambusStop.ts
GSREN3D-356 - Travel time page: wrong station display
https://jira.camptocamp.com/browse/GSREN3D-356
Before
After
> GSREN3D-356 - Travel time page: wrong station display

- package-lock.json
- package.json
- src/components/map/HeadToolbarTrambus.vue
- src/components/map/buttons/LoginButtons.vue
- src/components/map/buttons/NavigationButtons.vue
- src/components/ui/UiLineHeader.vue
- src/views/LineView.vue
https://jira.camptocamp.com/browse/GSREN3D-293
Add tabular navigation on buttons
> accessibility-tooltip-buttons

- src/components/__tests__/line/ThermometerStations.spec.ts
- src/components/ui/UiPhotoGalery.vue
- src/services/poi.spec.ts
- src/services/station.ts
- src/views/LineView.vue
https://jira.camptocamp.com/browse/GSREN3D-475
Resize PhotoGalery pictures and change the position when aside panel is open
> 475- Resize pictures and change position

- package-lock.json
- package.json
- src/components/__tests__/line/ThermometerStations.spec.ts
- src/components/map/buttons/NavigationButtons.vue
- src/services/poi.spec.ts
- src/services/station.ts
- src/views/LineView.vue
- src/views/TravelTimesView.vue
https://jira.camptocamp.com/browse/GSREN3D-506
Update common_ui in package.json. ( + tiny bug on travelTime view)
> 506- Update common_ui

- package-lock.json
- package.json
- src/components/__tests__/home/__snapshots__/ConsultationComponent.spec.ts.snap
- src/components/home/ConsultationComponent.vue
https://jira.camptocamp.com/browse/GSREN3D-495
correct typo
> 495- Fix typo and update package.json

- src/stores/panels.ts
- src/views/HomeView.vue
https://jira.camptocamp.com/browse/GSREN3D-475
Fix display of pictures on the toggle on the side panel
/home/alettelier/Vidéos/kazam_vgujp7w5.movie.avi
> 475- Fix display pictures when side panel is toggled

- src/components/map/MapComponent.vue
- src/components/map/buttons/NavigationButtons.vue
- src/stores/stations.ts
https://jira.camptocamp.com/browse/GSREN3D-479
Add reset zoom button
> 479- Update compass

- src/App.vue
- src/components/home/ConsultationComponent.vue
- src/components/home/SidePanel.vue
- src/model/views.model.ts
- src/router/index.ts
- src/views/ConsultationView.vue
https://jira.camptocamp.com/browse/GSREN3D-488
Add consultationView
> 488- Add consulattionView with empty sidepanel

- src/assets/icons/travel-map.svg
- src/components/map/buttons/NavigationButtons.vue
https://jira.camptocamp.com/browse/GSREN3D-484
Add city map button on 3D
> 484- Add city map button

- README.md
https://jira.camptocamp.com/browse/GSREN3D-488
Fix branch error after remove retractable arrow on consultation panel
> 488- Fix branch error

- src/services/viewStyle.ts
- src/styles/line.ts
https://jira.camptocamp.com/browse/GSREN3D-432
Remove white border on trambus lines in 3D
> 432- Remove white border on trambus lines in 3D

- src/components/map/buttons/NavigationButtons.vue
- src/map.config.json
- src/stores/layers.ts
- src/stores/map.ts
https://jira.camptocamp.com/browse/GSREN3D-473
Display or remove alternative background when toggle map button
> 473- Alternative background

- src/components/legal/HeaderLegalNotice.vue
- src/views/LineView.vue
- src/views/StationView.vue
https://jira.camptocamp.com/browse/GSREN3D-483
Add missing footer links in LineView and StationView
> 483- Add missing footer in LineView and StationView

- package-lock.json
- package.json
- src/styles/common.ts
https://jira.camptocamp.com/browse/GSREN3D-433
change poi size
> 433- Change poi size

- src/components/ui/UiPlanningLegend.vue
https://jira.camptocamp.com/browse/GSREN3D-478
Link between radio button and map labels
> 478- Fix link between radio button and map label

- src/components/ui/UiPlanningLegend.vue
https://jira.camptocamp.com/browse/GSREN3D-478
Fix toggle on map label (planning view)
> 478- Fix toggle map label

- src/components/__tests__/map/planning/PlanningLegend.spec.ts
- src/components/ui/UiPlanningLegend.vue
- src/services/api.client.ts
https://jira.camptocamp.com/browse/GSREN3D-372
https://jira.camptocamp.com/browse/GSREN3D-478
Fix linked data to the wfs : remove duplicate stations : GSREN3D-372
Fix css issue on legend of planningview : GSREN3D-478
> 372- Fix linked data to the wfs

- src/map.config.json
https://jira.camptocamp.com/browse/GSREN3D-507
same configuration as solar use case
> 507- Change configuration ortho

- src/components/__tests__/consultation/__snapshots__/ConsultationMeeting.spec.ts.snap
- src/components/consultation/ConsultationMeeting.vue
- src/views/ConsultationView.vue
https://jira.camptocamp.com/browse/GSREN3D-493
https://jira.camptocamp.com/browse/GSREN3D-490
Add cursor pointer on arrow (consultation view)
Add line break (consultationMeeting)
> Css changes

- src/components/map/buttons/NavigationButtons.vue
fix Button reset zoom : inclinaison
https://jira.camptocamp.com/browse/GSREN3D-541
> fix Button reset zoom : inclinaison

- src/components/map/buttons/OlNavigationButtons.vue
https://jira.camptocamp.com/browse/GSREN3D-562
Change zoom in and zoom out button on Planning Page
> 562- Change button on planning page

- public/staticLabels.geojson
- src/components/map/MapComponent.vue
- src/components/map/aboveMap/ComponentsAboveMap.vue
- src/stores/interactionMap.ts
- tests/RennesAppTest.ts
https://jira.camptocamp.com/browse/GSREN3D-534
- Add a static label for the trambus line on the home page
- Only show the selected line on the line view
> GSREN3D-534: Add static label

- src/components/map/MapComponent.vue
- src/map.config.json
- src/services/RennesApp.ts
https://jira.camptocamp.com/browse/GSREN3D-566
change background color when tiles are missing
> 566- Change color on initialize

- src/components/__tests__/consultation/__snapshots__/ProjectMeeting.spec.ts.snap
- src/components/consultation/ProjectMeeting.vue
- src/components/map/MapComponent.vue
- src/components/map/aboveMap/ComponentsAboveMap.vue
- src/map.config.json
- src/services/RennesApp.ts
- src/stores/layers.ts
- src/views/ConsultationView.vue
- src/views/HomeView.vue
- src/views/LineView.vue
- src/views/StationView.vue
- src/views/TravelTimesView.vue
https://jira.camptocamp.com/browse/GSREN3D-494
- add missing properties for consultation
- fix UI issue
- add a new layer to show the geometry of a consultation on hover
Hovered on the _Boite a idees TRAMBUS_
> GSREN3D-494: update concertation UI and show its geometry

- src/App.vue
- src/components/home/FooterPlainPage.vue
- src/components/legal/AccessibilityLegal.vue
- src/components/legal/CGULegal.vue
- src/components/legal/CookiesLegal.vue
- src/components/legal/LegalNotice.vue
- src/components/legal/PrivacyLegal.vue
- src/components/legal/SiteMap.vue
- src/constants/legalLinks.ts
- src/router/index.ts
- src/views/HomeView.vue
- src/views/LegalNoticeView.vue
- src/views/LineView.vue
- src/views/StationView.vue
https://jira.camptocamp.com/browse/GSREN3D-681
> GSREN3D-681: link content update and bug fixing

- src/components/map/planning/PlanningMapComponent.vue
- src/main.ts
- src/services/api-config.ts
- src/stores/config.ts
https://jira.camptocamp.com/browse/GSREN3D-693
> GSREN3D-693: Use config for project planning urls.

- src/main.ts
https://jira.camptocamp.com/browse/GSREN3D-693
> GSREN3D-693: Use router after getting configuration.

- src/map.config.json
https://jira.camptocamp.com/browse/GSREN3D-XXX
> Update POI data source

- src/components/home/TravelTimes.vue
- src/map.config.json
- tailwind.config.cjs
https://jira.camptocamp.com/browse/GSREN3D-XXX
> GSREN3DSUP-51

- src/services/line.ts
https://jira.camptocamp.com/browse/GSREN3DSUP-57
> fix: start and end stations computing
